apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: terraria
resources:
  - rbac.yaml
  - deployment.yaml
  - service.yaml
configMapGenerator:
  - name: world-creator-ui-code
    files:
      - code/server.py
      - code/index.html
      - code/styles.css
      - code/app.js
      - code/upload-world.sh
generatorOptions:
  disableNameSuffixHash: true
